jwt:  #jwt 관련 정보
  key: ${JWT_SECRET_KEY}

mail: #관리자 권한 메일
  address:
    admin: qudtn7383@gmail.com, zzz@gmail.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-1
    stack:
      auto: false

application:
  bucket:
    name: sebmain007

server:
  ssl:
    key-store: /root/farm.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
