jwt:  #jwt 관련 정보
  key: ${{secrets.JWT_SECRET_KEY}}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

mail: #관리자 권한 메일
  address:
    admin: admin@gmail.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${{secrets.G_CLIENT_ID}}
            clientSecret: ${{secrets.G_CLIENT_SECRET}}
            scope:
              - email
              - profile

