# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: application-prod.yml 생성
      run: echo "${{ secrets.PROD_YML }}" > ./src/main/resources/application-prod.yml
      working-directory: ./server/farm
      
    - name: application-secret.yml 생성
      run: echo "${{ secrets.SECRET_YML }}" > ./src/main/resources/application-secret.yml
      working-directory: ./server/farm

    - name: Grand execute permission for gradlew
      run: chmod +x /root/actions-runner/_work/seb41_main_007/seb41_main_007/server/farm/gradlew

    # - name: Setup MySQL
    #   uses: samin/mysql-action@v1
    #   with:
    #     character set server: 'utf8' 
    #     mysql version: '8.0'
    #     mysql database: ${{ secrets.DATABASE_URL }}
    #     mysql user: ${{ secrets.DATABASE_USER }}
    #     mysql password: ${{ secrets.DATABASE_PASSWORD }}

    - name: build
      run: /root/actions-runner/_work/seb41_main_007/seb41_main_007/server/farm/gradlew build --warning-mode all
      working-directory: ./server/farm

    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:8080` & sudo java -jar /root/actions-runner/_work/seb41_main_007/seb41_main_007/server/farm/build/libs/farm-0.0.1-SNAPSHOT.jar &
